# Generated by Django 4.0.3 on 2022-04-21 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='x_label',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='y_label',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
