# Generated by Django 4.0.3 on 2022-04-21 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0002_event_x_label_event_y_label'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='x_label',
            new_name='x_label_max',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='y_label',
            new_name='x_label_min',
        ),
    ]
