# Generated by Django 4.0.3 on 2022-03-21 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('host', '0001_initial'),
        ('user_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='host.answerchoice')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_mgmt.anonymousparticipant')),
            ],
        ),
    ]
